### ISSUE TITLE
Document how to use this toolkit

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/Excel_Toolkit#26]
Currently, no documentation exists 😄 

This means people wanting to know how to use this toolkit rely on others with the tribal knowledge (to coin a @pawelbaran phrase).

We need some wiki documentation or other user guides to help users understand how to build up requests for this toolkit.

**Comment by travispotterBH** [comment]
@desaiwangBH  work for week of 6/26 - 6/30

**Comment by albinber** [comment]
Notes:
Data is pulled row by row, not column by column
There is two options for getting cell contents
range needs to be expression1:expression2, as in if you want to pull just one cell you need to put A3:A3 for example.
Whenever doing changes to the excel sheet, save the file and toggle active on and off to update in GH.
