### ISSUE TITLE
Exceptions on creating Excel files

### ISSUE THREAD

**Issue by vietle-bh** [BHoM/Excel_Toolkit#64]
#### Description:

I got 2 exceptions in the order below while exporting data from a BIM application to Excel:

![image](https://github.com/BHoM/Excel_Toolkit/assets/102604891/2809e6fd-9583-4024-ad81-f745671841e3)

![image](https://github.com/BHoM/Excel_Toolkit/assets/102604891/8d8fb1bd-a2d7-4df2-82e4-e98300848936)

**Comment by FraserGreenroyd** [comment]
Linked to #63

**Comment by vietle-bh** [comment]
This was resolved together with https://github.com/BHoM/Excel_Toolkit/issues/63

**Comment by vietle-bh** [comment]
This was resolved together with https://github.com/BHoM/Excel_Toolkit/issues/63
